jobs:
  ci:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Run Android tests
      uses: reactivecircus/android-emulator-runner@e790971012b979513b4e2fe70d4079bc0ca8a1ae
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        script: ./gradlew connectedAndroidTest --stacktrace
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: instrumentation-test-results ${{ matrix.api-level }}
        path: ./**/build/reports/androidTests/connected/**
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SonatypePassword }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SonatypeUsername }}
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      name: Upload snapshot (master only)
      run: ./gradlew publish
    strategy:
      fail-fast: false
      matrix:
        api-level:
        - 29
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
permissions:
  contents: read
